# Generated by Django 6.0.6 on 2026-06-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('eaddr', models.CharField(max_length=50)),
                ('eno', models.IntegerField()),
                ('esal', models.FloatField()),
            ],
        ),
    ]
